spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}

  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASS}
    baseline-on-migrate: true
    locations: classpath:db/migration

  sql:
    init:
      mode: never

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    "[org.springframework.r2dbc.core]": DEBUG
    "[io.r2dbc.postgresql]": DEBUG
